Feature/token
svtechnmaa/charts pull request #26
Opened 2024-10-30 09:00 UTC by duchieu2k

feat: Add fine-granted token to clone repos and edit 'stack' as an immutable variable

2024-10-31 04:37 UTC, tuhoanganh requested changes

2024-10-31 04:37 UTC, tuhoanganh commented on kubernetes/preparation/templates/secret.yaml
Cái này có cần đổi env name cho bớt confused ko?

2024-10-31 04:37 UTC, tuhoanganh commented on kubernetes/streamlit/templates/deploy.yaml
Cái này có cần đổi env name cho bớt confused ko?

2024-10-31 04:37 UTC, tuhoanganh commented on kubernetes/streamlit/templates/init-repo.yaml
Cái này có cần đổi env name cho bớt confused ko?

2024-11-01 02:31 UTC, vyvuvivo approved these changes

2024-11-01 07:32 UTC, tuhoanganh approved these changes
+1

2024-11-01 07:34 UTC, merged

2025-10-07 10:24 UTC, SVTECH-NMAA commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/svtechnmaa/charts/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: